In [1]:
import numpy as np

# create a numPy array
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


* Creates a 3*3 array filled with zeros

In [6]:
zeros_arr = np.zeros((3,2)) # tuple(3,2) is converted into array of ZEROS 3*2

print(zeros_arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:
# create a numPy array filled with ones
ones_arr = np.ones((2,2)) # tuple(2,2) is converted into array of ONES 2*2
print(ones_arr)
ones_arr[1][1]

[[1. 1.]
 [1. 1.]]


1.0

* np.arange()

In [19]:
# Table of 2
arr = np.arange(2,21,2)
print("Array from arange:", arr)

# Table of 3
arr = np.arange(3,31,3)
print("Array from arange:", arr)

Array from arange: [ 2  4  6  8 10 12 14 16 18 20]
Array from arange: [ 3  6  9 12 15 18 21 24 27 30]


* np.linespace()

In [10]:
line_array = np.linspace(0,2,10) #create a array with same range/gap from 0 to 2

print("Array from linespace:",line_array)

Array from linespace: [0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [21]:
# table of 3 with line space
table_of_three = np.linspace(3,30,10)
print(table_of_three)

# table of 3 with line space till 20
table_of_three = np.linspace(3,60,20)
print(table_of_three)

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30.]
[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36. 39. 42. 45. 48. 51. 54.
 57. 60.]


np.random()

In [25]:
random = np.random.rand(3,3) # by default value are from 0 to 1
print(random)

print()

rand_arr = 20 + np.random.rand(3,3) * 10
print(rand_arr)

[[0.52522493 0.4508898  0.22336352]
 [0.96791073 0.06162023 0.56865873]
 [0.8442617  0.53316682 0.82333548]]

[[28.62321238 25.50354971 24.55987884]
 [22.33152673 28.28934719 24.84886065]
 [22.85162015 21.94947554 24.63299673]]


In [29]:
# Generate values from 500 to 1000
values = 500 + np.random.rand(3,3)*500
print(values)

[[783.45507165 908.55384269 760.59973422]
 [814.44638386 768.71630501 526.22794351]
 [880.82933987 541.44231064 908.15883123]]


* ndim = 2
* shape
* reshape

In [15]:
import numpy as np
arr = np.array([1,2,3,4], ndmin = 2)

print(arr)
print(arr.shape)

print()
reshap_arr = arr.reshape((2,2))
print(reshap_arr)

print()
reshap_arr = arr.reshape((4,1))
print(reshap_arr,reshap_arr[2][0]) # Access 3

[[1 2 3 4]]
(1, 4)

[[1 2]
 [3 4]]

[[1]
 [2]
 [3]
 [4]] 3


In [17]:
# to check the dimension of array
print(arr.ndim)

2


* Data Types in numPy

In [19]:
# All the values will be string when we define the datatype dtype = np.str_
str_arr = np.array(["ABC","DEF",89] , dtype = np.str_) # _ underscore is part of string
print("String array:", str_arr)
print(type(str_arr))


String array: ['ABC' 'DEF' '89']
<class 'numpy.ndarray'>


In [22]:
# All the numbers converted to int64
int_arr = np.array([1,2,3,8.0], dtype = np.int64, ndmin = 2)
print(int_arr)

[[1 2 3 8]]


In [23]:
# All the float_numbers converted to float64
int_arr = np.array([1,2,3,8.0], dtype = np.float64, ndmin = 2)
print(int_arr)

[[1. 2. 3. 8.]]


In [24]:
# 0 --> False  1 --> True 
# False in '0' , All others are True
bool_arr = np.array([True,False,True,7], dtype = np.bool_) 
print("Boolean array:", bool_arr)

Boolean array: [ True False  True  True]


* ASCII codes [ord] 
* character [chr]

In [27]:

print(ord('A'))
print(ord('a'))
print(ord('@'))

print(chr(65))
print(chr(67))

65
97
64
A
C


In [28]:
# To check the data type
arr = np.array([1,2,3,4])
print(arr.dtype)

int32


In [35]:
arr = np.array(['dogs','cats','horses'] , dtype='S')
print(arr.dtype) # |S6

arr = np.array(['dogs','cats','horses'] , dtype='str')
print(arr.dtype) # <U6

|S6
<U6


* slicing

In [38]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]], ndmin = 2)

print(arr.ndim)

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr.ndim)

2
2


* access elements

In [41]:
element = arr[2,1] # more easy
print(element)

element = arr[2][1]
print(element)

element = arr[2,2] # more easy
print(element)

8
8
9


In [43]:
print("Element at First row and second column:", arr[0,1])

Element at First row and second column: 2


In [59]:
# For all the columns
# Access [4,5,6]
arr[1,:]
print(arr[1,:])

# Access [4,5]
arr[1,:]
print(arr[1,:-1])

# Access [4,5]
arr[1,:]
print(arr[1,:2])

# Access [3,6,9]
print(arr[:,2])

# Access [8,9]
print(arr[2, 1:3])

# Access [4,5,6] [7,8,9]
print(arr[1:3,:])

[4 5 6]
[4 5]
[4 5]
[3 6 9]
[8 9]
[[4 5 6]
 [7 8 9]]


In [61]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]], ndmin = 2)

mask = arr > 5
print("Boolean mask for values greater than 5: \n",mask)
filtered = arr[mask]
print("Values greater than 5: \n", filtered)


Boolean mask for values greater than 5: 
 [[False False False]
 [False False  True]
 [ True  True  True]]
Values greater than 5: 
 [6 7 8 9]


In [65]:
a = np.array([1,2,3,4],
             [5,6,7,8],
             [9,10,11,12])
# SLICING
b = a[:2,1:3]
c = a[1:,:1]
d = a[2:,2:]

print("Sliced Array:")
print(b)
print(c,'\n',d)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [86]:
# Problem: Generate
# {'a':1 , 'b' : 2 , ...... , 'z',26}

print(ord('a'))

emp_dict = {}
for i in range(1,27):
    emp_dict[chr(96+i)] = i
print(emp_dict)

dict_comp1 = {chr(96+i):i for i in range(1,27)}
print(dict_comp1)
 
dict_comp2 = {chr(i):i-96 for i in range(ord('a'),ord('z')+1)}
print(dict_comp2)

print(chr(1))

97
{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26}
{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26}
{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26}



In [5]:
# Problem: swap key and value position
dict =  {'a':1 , 'b':2 , 'c':3}
emp_dict = {}
for i,j in dict.items():
    emp_dict[j] = i
print(emp_dict)

dict_comp = {j:i for i,j in dict.items()}
print(dict_comp)

{1: 'a', 2: 'b', 3: 'c'}
{1: 'a', 2: 'b', 3: 'c'}
