# Introduction to Numpy

NumPy (Numerical Python) is a fundamental library in Python for numerical and scientific computing.
It provides support for arrays, matrices, and a wide range of mathematical functions to work efficiently with large datasets and perform various mathematical operations

# Creating NumPy Array

### From List to Tuples

In [1]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Convert NumPy array to pandas DataFrame
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [1]:
!pip3 install numpy


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


### Using Built-in Functions

### Creates a 3x3 array filled with zeros

In [11]:
import numpy as np

# Create a NumPy array filled with zeros
zeros_arr = np.zeros((3, 2))

# Convert NumPy array to pandas DataFrame
print(zeros_arr)


[[0. 0.]
 [0. 0.]
 [0. 0.]]


### Creates a 2x2 array filled with ones

In [2]:
import numpy as np

# Create a NumPy array filled with ones
ones_arr = np.ones((2, 2))

# Convert NumPy array to pandas DataFrame
print(ones_arr)
ones_arr[1][1]


[[1. 1.]
 [1. 1.]]


1.0

### np.arange() and np.linspace() are NumPy functions used to create arrays with a sequence of numbers.

### np.arange()

In [3]:
import numpy as np

# Create array using arange
arr = np.arange(0, 11, 2)  # Creates an array [0, 2, 4, 6, 8]

# Print the array
print("Array from arange:")
print(arr)


Array from arange:
[ 0  2  4  6  8 10]


### np.linspace()

In [7]:
import numpy as np

# Create array using linspace
lin_arr = np.linspace(3, 60, 20)  # Creates an array [0.  , 0.25, 0.5 , 0.75, 1.  ]

# Print the array
print("Array from linspace:")
print(lin_arr)


Array from linspace:
[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36. 39. 42. 45. 48. 51. 54.
 57. 60.]


### Random Arrays - Random arrays are arrays whose elements are generated randomly. 

### Creates a 3x3 array with random values between 0 and 1

In [10]:
import numpy as np

random = np.random.rand(3, 3)
print(random)

# Create a 3x3 array with random values between 0 and 1
print(np.random.rand(3, 3) * 10)
rand_arr = 20 + np.random.rand(3, 3) * 10

# Print the random array
print(rand_arr)


[[0.56699701 0.46528853 0.40534777]
 [0.61527542 0.5340696  0.67526586]
 [0.68337189 0.17484807 0.00677246]]
[[8.30912057 5.04804841 6.4863223 ]
 [4.97077366 6.2444297  2.64155339]
 [8.97302637 7.26719    9.13225012]]
[[25.15364807 21.40526269 22.06073669]
 [24.51482709 26.02828593 22.54867862]
 [28.36909156 27.976847   21.29393863]]


### Using Dimension to generate N-dimensional arrays

In [16]:
import numpy as np

# Create a 2-dimensional array with specified dimensions
arr = np.array([1, 2, 3, 4], ndmin=2)

# Print the array
print(arr)
print(arr.shape)

[[1 2 3 4]]
(1, 4)


### The reshape() method in NumPy allows you to change the shape of an array

In [26]:
import numpy as np

# Create a 2-dimensional array with specified dimensions
arr = np.array([1, 2, 3, 4], ndmin=2)
print(arr)

# Reshape the array to a 2x2 shape
reshaped_arr = arr.reshape((4, 1))

# Print the reshaped array
print(reshaped_arr)
print(reshaped_arr[3][0])


[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
4


###  You can check the type of the array object using the type() function in Python.

In [12]:
import numpy as np

# Create a 2-dimensional array with specified dimensions
arr = np.array([1, 2, 3, 4], ndmin=2)

# Print the type of the array object
print(type(arr))


<class 'numpy.ndarray'>


### You can use the shape attribute of a NumPy array to check its dimensions.

In [13]:
import numpy as np

# Create a 2-dimensional array with specified dimensions
arr = np.array([1, 2, 3, 4], ndmin=2)

# Print the shape of the array
print(arr.shape)


(1, 4)


### You can use the ndim attribute of a NumPy array to check its number of dimensions.

In [14]:
import numpy as np

# Create a 2-dimensional array with specified dimensions
arr = np.array([1, 2, 3, 4], ndmin=2)

# Print the number of dimensions of the array
print(arr.ndim)


2


### Data Types in NumPy

### Strings are sequences of characters, such as letters, numbers, symbols, or spaces, enclosed within single quotes (') or double quotes (").

In [28]:
import numpy as np

# Create a NumPy array of strings
str_arr = np.array(['ABC', 'DEF', 89], dtype=np.str_)

# Print the array
print("String array:", str_arr)
print(type(str_arr))


String array: ['ABC' 'DEF' '89']
<class 'numpy.ndarray'>


### Integers are whole numbers, positive or negative, without any decimal point. 

In [21]:
import numpy as np

# Create a NumPy array of integers
int_arr = np.array([1, 2, 3, 8.0], dtype=np.int64, ndmin=2)

# Print the array
print("Integer array:", int_arr)


Integer array: [[1 2 3 8]]


### Floats (floating-point numbers) are numbers that have a decimal point or use exponential (scientific) notation. They can represent both integer and fractional parts of numbers. 

In [14]:
import numpy as np

# Create a NumPy array of floats
float_arr = np.array([5.98, 3.14, 67], dtype=np.float64)

# Print the array
print("Float array:", float_arr)


Float array: [ 5.98  3.14 67.  ]


### Booleans are a data type that represents one of two possible values: True or False.

In [23]:
import numpy as np

# Create a NumPy array of booleans
bool_arr = np.array([True, False, True, 7], dtype=np.bool_)

# Print the array
print("Boolean array:", bool_arr)


Boolean array: [ True False  True  True]


In [51]:
print(ord('a'))
print(chr(65))

97
A


### Complex numbers consist of a real part and an imaginary part, where the imaginary part is represented by the letter j or J.

In [16]:
import numpy as np

# Create a NumPy array of complex numbers
complex_arr = np.array([1.0 + 2.0j, 3.0 + 4.0j], dtype=np.complex128)

# Print the array
print("Complex array:", complex_arr)
print(type(complex_arr))


Complex array: [1.+2.j 3.+4.j]
<class 'numpy.ndarray'>


### Creating NumPy arrays with specific data types using the dtype parameter. 

### Creating an array of integers without specifying the data type:

In [52]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)  # int32


int32


### Creating an array of strings with a specific data type ('S' for strings):

In [54]:
arr = np.array(['dogs', 'cats', 'horses'], dtype='S')
print(arr.dtype)  # |S6


|S6


# Indexing and Slicing NumPy Arrays


### NumPy arrays can be accessed and sliced similar to Python lists, with the additional ability to index and slice in multiple dimensions for multi-dimensional arrays.


### Create a Numpy Array

In [55]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]], ndmin=2)
print(arr.ndim)

2


### Accessing elements

In [57]:
element = arr[1, 0]  # Accessing the element at the first row and second column
print("Element at first row and second column:", element)

Element at first row and second column: 4


### Slicing Rows

In [71]:
slice_row = arr[1:3, :]  # Slicing the second row
print("Second row:", slice_row)

Second row: [[4 5 6]
 [7 8 9]]


### Slicing Columns


In [46]:
slice_column = arr[0:2,:]  # Slicing the third column
print("Third column:", slice_column)

Third column: [[1 2 3]
 [4 5 6]]


### Advanced indexing with boolean masking

In [27]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]], ndmin=2)

mask = arr > 5  # Creating a boolean mask for values greater than 5
print("Boolean mask for values greater than 5:\n", mask)
filtered = arr[mask]  # Getting values greater than 5
print("Values greater than 5:\n", filtered)

Boolean mask for values greater than 5:
 [[False False False]
 [False False  True]
 [ True  True  True]]
Values greater than 5:
 [6 7 8 9]


### Create the following rank 2 array with shape (3, 4)


In [28]:
import numpy as np

# Given NumPy array
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Print the array
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2; b is the following array of shape (2, 2):


In [73]:
import numpy as np

# Given NumPy array
a = np.array([[1, 2, 3, 4],
              [4, 6, 7, 8],
              [9, 10, 11, 12]])

# Slicing the array
b = a[:2, 1:3]
c = a[1:,  :1]
d = a[2:, 2:]

# Print the sliced array
print("Sliced array b:")
print(b)
print(c, '\n', d)


Sliced array b:
[[2 3]
 [6 7]]
[[4]
 [9]] 
 [[11 12]]


### A slice of an array is a view into the same data, so modifying it will modify the original array.


In [74]:
import numpy as np

# [[2 3]
#  [6 7]]

# Given NumPy array
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

a[1][2]
a[1,2]

# Slicing the array
b = a[:2, 1:3]

print(b)

# Print element of a
print("Element of a[0, 1]:", a[0, 1])   # Prints "2"

# Modify element of b
b[0, 1] = 77     # b[0, 0] is the same piece of data as a[0, 1]

# Print modified element of a
print(a)   # Prints "77"


[[2 3]
 [6 7]]
Element of a[0, 1]: 2
[[ 1  2 77  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Numpy Operations

### NumPy arrays support a wide range of operations, including arithmetic, statistical, and more. These operations are performed element-wise.


### Element-wise arithmetic operations - In element-wise operations, corresponding elements of the input structures are operated on together to produce an output structure of the same shape.


In [36]:
import numpy as np

# Given NumPy arrays
arr1 = np.array([1, 2, 3])  # Define the first NumPy array
arr2 = np.array([4, 5, 6])  # Define the second NumPy array



### Element-wise Addition:It refers to the process of adding corresponding elements of two arrays, matrices, or vectors together to produce a new array, matrix, or vector of the same shape.

In [37]:
addition = arr1 + arr2  # Perform element-wise addition
print("Element-wise addition:", addition)  # Print the result of addition


Element-wise addition: [5 7 9]


### Element-wise Subtraction:It is similar to element-wise addition, but instead of adding corresponding elements, it involves subtracting them.

In [41]:
subtraction = arr1 - arr2  # Perform element-wise subtraction
print("Element-wise subtraction:", subtraction)  # Print the result of subtraction


Element-wise subtraction: [-3 -3 -3]


### Element-wise Multiplication: It is a mathematical operation in which corresponding elements of two arrays, matrices, or vectors are multiplied together to produce a new array, matrix, or vector of the same shape.

In [42]:
multiplication = arr1 * arr2  # Perform element-wise multiplication
print("Element-wise multiplication:", multiplication)  # Print the result of multiplication


Element-wise multiplication: [ 4 10 18]


### Element-wise Division: It is a mathematical operation where corresponding elements of one array, matrix, or vector are divided by corresponding elements of another array, matrix, or vector, resulting in a new array, matrix, or vector of the same shape.

In [43]:
division = arr1 / arr2  # Perform element-wise division
print("Element-wise division:", division)  # Print the result of division


Element-wise division: [0.25 0.4  0.5 ]


### Statistical operations


### Statistical operations refer to various mathematical procedures used to analyze, interpret, summarize, and draw conclusions from data.

In [35]:
import numpy as np

# Given NumPy arrays
arr1 = np.array([1, 2, 3])  # Define the first NumPy array
arr2 = np.array([4, 5, 6])  # Define the second NumPy array

# Calculate mean and standard deviation
mean_arr1 = np.mean(arr1)  # Calculate the mean of arr1
std_dev_arr2 = np.std(arr2)  # Calculate the standard deviation of arr2

# Print results
print("Mean of arr1:", mean_arr1)  # Print the mean of arr1
print("Standard deviation of arr2:", std_dev_arr2)  # Print the standard deviation of arr2


Mean of arr1: 2.0
Standard deviation of arr2: 0.816496580927726


### Geometric Operations

### Exponentiation: Raises each element of the array to the power of Euler's number.

In [44]:
import numpy as np

arr1 = np.array([1, 2, 3])  # Define the input array
result_exp = np.exp(arr1)   # Compute element-wise exponentiation
print("Exponentiation of arr1:", result_exp)


Exponentiation of arr1: [ 2.71828183  7.3890561  20.08553692]


### Square Root: Computes the square root of each element in the array.

In [45]:
import numpy as np

arr1 = np.array([4, 9, 16])  # Define the input array
result_sqrt = np.sqrt(arr1)  # Compute element-wise square root
print("Square root of arr1:", result_sqrt)


Square root of arr1: [2. 3. 4.]


### Sine: Computes the sine of each element in the array treated as angles in radians.

In [46]:
import numpy as np

arr1 = np.array([0, np.pi/2, np.pi])  # Define the input array (angles in radians)
result_sin = np.sin(arr1)             # Compute element-wise sine
print("Sine of arr1:", result_sin)


Sine of arr1: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


### Cosine: Computes the cosine of each element in the array treated as angles in radians.

In [47]:
import numpy as np

arr1 = np.array([0, np.pi/2, np.pi])  # Define the input array (angles in radians)
result_cos = np.cos(arr1)             # Compute element-wise cosine
print("Cosine of arr1:", result_cos)


Cosine of arr1: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


### Natural Logarithm: Computes the natural logarithm (base e) of each element in the array.

In [48]:
import numpy as np

arr1 = np.array([1, 2, 3])  # Define the input array
result_log = np.log(arr1)   # Compute element-wise natural logarithm
print("Natural logarithm of arr1:", result_log)


Natural logarithm of arr1: [0.         0.69314718 1.09861229]


### Aggregate Functions

### Sum: Computes the sum of all elements in the array.

In [49]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])  # Define the input array

# Sum of all elements in the array
sum_result = arr1.sum()
print("Sum of arr1:", sum_result)

Sum of arr1: 15


### Minimum: Finds the minimum value among all elements in the array.

In [50]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])  # Define the input array

# Minimum value among all elements in the array
min_result = arr1.min()
print("Minimum value in arr1:", min_result)

Minimum value in arr1: 1


### Maximum: Finds the maximum value among all elements in the array.

In [52]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])  # Define the input array

# Maximum value among all elements in the array
max_result = arr1.max()
print("Maximum value in arr1:", max_result)

Maximum value in arr1: 5


In [75]:
# {'a':1, 'b':2 ....... 'z':26}

dictionary = {chr(i):i-96 for i in range(ord('a'), ord('z')+1)}
print(dictionary)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26}


In [76]:
{'a':1, 'b': 2, 'c': 3}
# swap keys and values

{'a': 1, 'b': 2, 'c': 3}

# Panda Series

### Pandas is a Python library for data manipulation and analysis, offering data structures like Series and DataFrame for handling structured data efficiently,

### creating a pandas series

In [1]:
import pandas as pd

# Creating a Series from a list
data = [10, 20, 30, 40, 50]
series_from_list = pd.Series(data)
print(series_from_list)
print(type(series_from_list))


0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
!pip install pandas

In [33]:
import pandas as pd
import numpy as np

# Creating a Series from a NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])
series_from_numpy = pd.Series(numpy_array)
print(series_from_numpy)

0    1
1    2
2    3
3    4
4    5
dtype: int32


In [35]:
import pandas as pd

# Creating a Series with custom index labels
data = [10, 20, 30, 40, 50]
custom_index = pd.Series(data, index=['A', 'B', 'C', 'D', 'E'])
custom_index


A    10
B    20
C    30
D    40
E    50
dtype: int64

### Accessing elements by position (zero-based index)

This operation retrieves an element from a pandas Series based on its position, which follows a zero-based index (the first element has index 0, the second has index 1, and so on).

In [36]:
# Example:
element_at_position_2 = series_from_list[2]
print("Element at position 2:", element_at_position_2)


Element at position 2: 30


### Accessing elements by label

 - This operation retrieves an element from a pandas Series based on its label.
 - When you create a Series with custom index labels, you can access elements using these labels.

In [57]:
# Example:
element_with_label_B = custom_index['B']
print("Element with label 'B':", element_with_label_B)


Element with label 'B': 20


### Slicing a series

Slicing allows you to select a subset of elements from a Series based on their positions.

In [5]:
# Example:
slice_series = series_from_list[1:4]
print(slice_series)


1    20
2    30
3    40
dtype: int64


# Creating Pandas DataFrame

### Creating a DataFrame from a dictionary

In [7]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35]}

df_from_dict = pd.DataFrame(data)

# Print the DataFrame
print("DataFrame created from dictionary:")
display(df_from_dict)
display(type(df_from_dict))



DataFrame created from dictionary:


Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

pandas.core.frame.DataFrame

### Creating a DataFrame from a list of lists with custom column names


In [8]:
import pandas as pd

# Creating a DataFrame from a list of lists with custom column names
data_list = [['Alice', 25], 
             ['Bob', 30], 
             ['Charlie', 35]]
df_from_list = pd.DataFrame(data_list, columns=['Name', 'Age'])

# Print the DataFrame
print("DataFrame created from list of lists with custom column names:")
display(df_from_list)


DataFrame created from list of lists with custom column names:


Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

### Creating a DataFrame from a CSV file


In [11]:
import pandas as pd

# Creating a DataFrame from a CSV file
df_from_csv = pd.read_csv('data.csv')

# Print the DataFrame
print("DataFrame created from CSV file:")
display(df_from_csv)


DataFrame created from CSV file:


Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter   
1       2  1Ef7b82A4CAAD10    Preston    Lozano   
2       3  6F94879bDAfE5a6        Roy     Berry   
3       4  5Cef8BFA16c5e3c      Linda     Olsen   
4       5  053d585Ab6b3159     Joanna    Bender   
..    ...              ...        ...       ...   
95     96  cb8E23e48d22Eae       Karl     Greer   
96     97  CeD220bdAaCfaDf       Lynn  Atkinson   
97     98  28CDbC0dFe4b1Db       Fred    Guerra   
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer   
99    100  2354a0E336A91A1   Clarence    Haynes   

                            Company               City  \
0                   Rasmussen Group       East Leonard   
1                       Vega-Gentry  East Jimmychester   
2                     Murillo-Perry      Isabelborough   
3   Dominguez, Mcmillan and Donovan         Bensonview   
4          Martin, Lang and Andrade     West Priscilla   
..                              ...                ...   
95                        Carey LLC       East Richard   
96            Ware, Burns and Oneal       New Bradview   
97                    Schmitt-Jones         Ortegaland   
98               Fitzgerald-Harrell    Lake Elijahview   
99               Le, Nash and Cross          Judymouth   

                       Country                 Phone 1  \
0                        Chile            229.077.5154   
1                     Djibouti              5153435776   
2          Antigua and Barbuda         +1-539-402-0259   
3           Dominican Republic  001-808-617-6467x12895   
4   Slovakia (Slovak Republic)  001-234-203-0635x76146   
..                         ...                     ...   
95                      Guyana     (188)169-1674x58692   
96                   Sri Lanka         +1-846-706-2218   
97             Solomon Islands    +1-753-067-8419x7170   
98                       Aruba           (530)311-9786   
99                    Honduras           (753)813-6941   

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info        2020-08-24   
1         686-620-1820x944                 vmata@colon.com        2021-04-23   
2      (496)978-3969x58947             beckycarr@hogan.com        2020-03-25   
3          +1-813-324-8756     stanleyblackwell@benson.org        2020-06-02   
4    001-199-446-3860x3486         colinalvarado@miles.net        2021-04-17   
..                     ...                             ...               ...   
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30   
96            605.413.3198               vkemp@ferrell.com        2021-07-10   
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18   
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11   
99            783.639.1472          colleen91@faulkner.biz        2020-03-11   

                              Website  
0          http://www.stephenson.com/  
1               http://www.hobbs.com/  
2            http://www.lawrence.com/  
3          http://www.good-lyons.com/  
4         https://goodwin-ingram.com/  
..                                ...  
95            http://hayes-perez.com/  
96         https://novak-allison.com/  
97              https://www.ross.com/  
98               http://watkins.info/  
99  http://www.hatfield-saunders.net/  

[100 rows x 12 columns]

### Creating an empty DataFrame


In [13]:
import pandas as pd

# Creating an empty DataFrame
empty_df = pd.DataFrame()

# Print the empty DataFrame
print(empty_df)


Empty DataFrame
Columns: []
Index: []


# Indexing a Pandas DataFrame

### DataFrames allow for various methods of indexing, including selecting columns, filtering rows, and more.


### Selecting a single column


In [15]:
print(df_from_csv.columns)

# Selecting a single column
name_column = df_from_csv['Index']
print(name_column)


Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='object')
0       1
1       2
2       3
3       4
4       5
     ... 
95     96
96     97
97     98
98     99
99    100
Name: Index, Length: 100, dtype: int64


###  Selecting multiple columns


In [17]:
# Selecting multiple columns
subset = df_from_csv[['Index', 'Index']]
print(subset)


    Index  Index
0       1      1
1       2      2
2       3      3
3       4      4
4       5      5
..    ...    ...
95     96     96
96     97     97
97     98     98
98     99     99
99    100    100

[100 rows x 2 columns]


### Filtering Rows based on a condition

In [20]:
# Filtering rows based on a condition
young_people = df_from_csv[df_from_csv['Last Name'] == 'Berry']
display(young_people)


Index      Customer Id First Name Last Name        Company           City  \
2      3  6F94879bDAfE5a6        Roy     Berry  Murillo-Perry  Isabelborough   

               Country          Phone 1              Phone 2  \
2  Antigua and Barbuda  +1-539-402-0259  (496)978-3969x58947   

                 Email Subscription Date                   Website  
2  beckycarr@hogan.com        2020-03-25  http://www.lawrence.com/

### Accessing a specific cell by row and column label


In [22]:
# Accessing a specific cell by row and column label
cell_value = df_from_csv.at[99, 'Company']
print("Value at cell (row 0, column 'Name'):", cell_value)



Value at cell (row 0, column 'Name'): Le, Nash and Cross


# Loading Data from files


### SQL Databases - You can connect to SQL databases and retrieve data using Pandas.


In [73]:
from sqlalchemy import create_engine

In [74]:
# Create a database connection
engine = create_engine('sqlite:///database.db')

In [75]:
data_from_sql = pd.read_sql_query('SELECT * FROM tracks', engine)

In [76]:
data_from_sql

TrackId                                               Name  AlbumId  \
0           1            For Those About To Rock (We Salute You)        1   
1           2                                  Balls to the Wall        2   
2           3                                    Fast As a Shark        3   
3           4                                  Restless and Wild        3   
4           5                               Princess of the Dawn        3   
...       ...                                                ...      ...   
3498     3499  Pini Di Roma (Pinien Von Rom) \ I Pini Della V...      343   
3499     3500  String Quartet No. 12 in C Minor, D. 703 "Quar...      344   
3500     3501               L'orfeo, Act 3, Sinfonia (Orchestra)      345   
3501     3502  Quintet for Horn, Violin, 2 Violas, and Cello ...      346   
3502     3503                                      Koyaanisqatsi      347   

      MediaTypeId  GenreId                                           Composer  \
0               1        1          Angus Young, Malcolm Young, Brian Johnson   
1               2        1                                               None   
2               2        1  F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...   
3               2        1  F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...   
4               2        1                         Deaffy & R.A. Smith-Diesel   
...           ...      ...                                                ...   
3498            2       24                                               None   
3499            2       24                                     Franz Schubert   
3500            2       24                                 Claudio Monteverdi   
3501            2       24                            Wolfgang Amadeus Mozart   
3502            2       10                                       Philip Glass   

      Milliseconds     Bytes  UnitPrice  
0           343719  11170334       0.99  
1           342562   5510424       0.99  
2           230619   3990994       0.99  
3           252051   4331779       0.99  
4           375418   6290521       0.99  
...            ...       ...        ...  
3498        286741   4718950       0.99  
3499        139200   2283131       0.99  
3500         66639   1189062       0.99  
3501        221331   3665114       0.99  
3502        206005   3305164       0.99  

[3503 rows x 9 columns]

### Jason Files - JSON (JavaScript Object Notation) files are commonly used for semi-structured data.

In [5]:
import pandas as pd

# Reading data from a JSON file with specified encoding
data_from_json = pd.read_json('data.json')

# Print the DataFrame
print("DataFrame created from JSON file:")
data_from_json

DataFrame created from JSON file:


name language                id  \
0       Adeel Solangi   Sindhi  V59OF92YF627HFY0   
1       Afzal Ghaffar   Sindhi  ENTOCR13RSCLZ6KU   
2       Aamir Solangi   Sindhi  IAKPO3R4761JDRVG   
3       Abla Dilmurat   Uyghur  5ZVOEPMJUI4MB4EN   
4            Adil Eli   Uyghur  6VTI8X6LL0MMPJCC   
...               ...      ...               ...   
15835   Bhupesh Menon    Hindi  0CEPNRDV98KT3ORP   
15836    Rohini Vasav    Hindi  UEFML43TCGS04KWM   
15837    Sunil Kapoor    Hindi  VY2A0APGVHK5NAW2   
15838  Zamokuhle Zulu  isiZulu  XU7BX2F8M5PVZ1EF   
15839   Bhupesh Menon    Hindi  0CEPNRDV98KT3ORP   

                                                     bio  version  
0      Donec lobortis eleifend condimentum. Cras dict...     6.10  
1      Aliquam sollicitudin ante ligula, eget malesua...     1.88  
2      Vestibulum pharetra libero et velit gravida eu...     7.27  
3      Donec lobortis eleifend condimentum. Morbi ac ...     2.53  
4      Vivamus id faucibus velit, id posuere leo. Mor...     6.49  
...                                                  ...      ...  
15835  Maecenas tempus neque ut porttitor malesuada. ...     2.69  
15836  Ut accumsan, est vel fringilla varius, purus a...     9.30  
15837  Proin tempus eu risus nec mattis. Ut dictum, l...     8.04  
15838  Etiam congue dignissim volutpat. Phasellus tin...     8.39  
15839  Maecenas tempus neque ut porttitor malesuada. ...     2.69  

[15840 rows x 5 columns]

### HTML/Web Scraping: You can aslo Scrape data from HTML tables on webpages

In [13]:
import pandas as pd

# Reading tables from a webpage
data_from_html = pd.read_html('https://www.w3schools.com/html/html_tables.asp')[0]  # Adjust index as needed
print("Data scraped from HTML table:")
data_from_html


Data scraped from HTML table:


Company           Contact  Country
0           Alfreds Futterkiste      Maria Anders  Germany
1    Centro comercial Moctezuma   Francisco Chang   Mexico
2                  Ernst Handel     Roland Mendel  Austria
3                Island Trading     Helen Bennett       UK
4  Laughing Bacchus Winecellars   Yoshi Tannamuri   Canada
5  Magazzini Alimentari Riuniti  Giovanni Rovelli    Italy